# Generated by Django 5.2.12 on 2026-04-05 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("engagements", "0001_initial"),
        ("scanning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BreachRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_or_domain",
                    models.CharField(max_length=500, verbose_name="Email or Domain"),
                ),
                (
                    "breach_name",
                    models.CharField(max_length=255, verbose_name="Breach Name"),
                ),
                (
                    "breach_date",
                    models.DateField(blank=True, null=True, verbose_name="Breach Date"),
                ),
                (
                    "pwn_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pwned Accounts"
                    ),
                ),
                (
                    "data_classes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Data Classes"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="hibp", max_length=50, verbose_name="Source"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verified"),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breach_records",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Breach Record",
                "verbose_name_plural": "Breach Records",
                "ordering": ["-breach_date"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Informational"),
                        ],
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "cvss_score",
                    models.FloatField(blank=True, null=True, verbose_name="CVSS Score"),
                ),
                (
                    "cve_id",
                    models.CharField(blank=True, max_length=20, verbose_name="CVE ID"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("evidence", models.TextField(blank=True, verbose_name="Evidence")),
                (
                    "recommendation",
                    models.TextField(blank=True, verbose_name="Recommendation"),
                ),
                (
                    "references",
                    models.JSONField(
                        blank=True, default=list, verbose_name="References"
                    ),
                ),
                ("tool_source", models.CharField(blank=True, max_length=50)),
                ("raw_tool_output", models.TextField(blank=True)),
                (
                    "is_false_positive",
                    models.BooleanField(default=False, verbose_name="False Positive"),
                ),
                (
                    "remediation_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("remediated", "Remediated"),
                            ("accepted_risk", "Accepted Risk"),
                            ("wont_fix", "Won't Fix"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("remediation_notes", models.TextField(blank=True)),
                ("remediation_deadline", models.DateField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "epss_score",
                    models.FloatField(blank=True, null=True, verbose_name="EPSS Score"),
                ),
                (
                    "business_impact",
                    models.TextField(blank=True, verbose_name="Business Impact"),
                ),
                (
                    "attack_path",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Attack Path"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "affected_assets",
                    models.ManyToManyField(blank=True, to="scanning.discoveredasset"),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="scanning.scan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finding",
                "verbose_name_plural": "Findings",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EscalationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("method", models.CharField(max_length=50, verbose_name="Method")),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "escalated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalated_to_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.contact",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="findings.finding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation Record",
                "ordering": ["-created_at"],
            },
        ),
    ]
