# Generated by Django 5.2.12 on 2026-04-05 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("discovery", "Phase 1 - Discovery"),
                            ("enumeration", "Phase 2 - Enumeration"),
                            ("vuln_assess", "Phase 3 - Vulnerability Assessment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("progress", models.PositiveIntegerField(default=0)),
                ("error_log", models.TextField(blank=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan",
                "verbose_name_plural": "Scans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tool_name", models.CharField(max_length=50)),
                ("target", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("command", models.TextField(blank=True)),
                (
                    "output_file",
                    models.FileField(blank=True, upload_to="scan_output/%Y/%m/"),
                ),
                ("raw_output", models.TextField(blank=True)),
                ("parsed_results", models.JSONField(blank=True, default=dict)),
                ("exit_code", models.IntegerField(null=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_executions",
                        to="scanning.scan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Execution",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveredAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset_type", models.CharField(max_length=20)),
                ("value", models.CharField(max_length=500)),
                ("source_tool", models.CharField(max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "technology_stack",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Technology Stack"
                    ),
                ),
                (
                    "ssl_info",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="SSL/TLS Info"
                    ),
                ),
                (
                    "whois_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="WHOIS Data"
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        upload_to="screenshots/%Y/%m/",
                        verbose_name="Screenshot",
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovered_assets",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovered_assets",
                        to="scanning.scan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovered Asset",
                "verbose_name_plural": "Discovered Assets",
                "unique_together": {("engagement", "asset_type", "value")},
            },
        ),
    ]
