# Generated by Django 5.2.12 on 2026-04-06 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[("passive", "Passive Recon"), ("full", "Full Recon")],
                        max_length=10,
                        verbose_name="Assessment Type",
                    ),
                ),
                ("phase_number", models.IntegerField(verbose_name="Phase Number")),
                (
                    "phase_name",
                    models.CharField(max_length=100, verbose_name="Phase Name"),
                ),
                (
                    "step_number",
                    models.CharField(max_length=10, verbose_name="Step Number"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("commands", models.TextField(blank=True, verbose_name="Commands")),
                (
                    "expected_input",
                    models.TextField(blank=True, verbose_name="Expected Input"),
                ),
                (
                    "expected_output",
                    models.TextField(blank=True, verbose_name="Expected Output"),
                ),
                ("order", models.IntegerField(verbose_name="Order")),
            ],
            options={
                "verbose_name": "Assessment Step",
                "verbose_name_plural": "Assessment Steps",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[("passive", "Passive Recon"), ("full", "Full Recon")],
                        default="passive",
                        max_length=10,
                        verbose_name="Assessment Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("executed", "Executed - Pending Report"),
                            ("pending_review", "Pending Review"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scope_text",
                    models.TextField(
                        help_text="Free-text scope: domains, IPs, CIDRs, emails, etc. One per line.",
                        verbose_name="Scope",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        upload_to="assessment_reports/%Y/%m/",
                        verbose_name="Report File",
                    ),
                ),
                ("report_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="engagements.engagement",
                        verbose_name="Engagement",
                    ),
                ),
                (
                    "report_uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_assessment_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentStepProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_progress",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_assessment_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="assessments.assessmentstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step Progress",
                "verbose_name_plural": "Step Progress",
                "ordering": ["step__order"],
                "unique_together": {("assessment", "step")},
            },
        ),
    ]
