# Generated by Django 5.2.12 on 2026-04-05 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Client Name")),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Industry"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("prospect", "Prospect"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Registration Number"
                    ),
                ),
                (
                    "registration_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Registration Country"
                    ),
                ),
                (
                    "officers",
                    models.JSONField(blank=True, default=list, verbose_name="Officers"),
                ),
                (
                    "social_media",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Social Media"
                    ),
                ),
                (
                    "domains_owned",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Domains Owned"
                    ),
                ),
                (
                    "ip_ranges",
                    models.JSONField(
                        blank=True, default=list, verbose_name="IP Ranges"
                    ),
                ),
                (
                    "dns_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="DNS Summary"
                    ),
                ),
                (
                    "certificate_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Certificate Summary"
                    ),
                ),
                (
                    "whois_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="WHOIS Data"
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Phone"),
                ),
                ("role", models.CharField(max_length=100, verbose_name="Role")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary Contact"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("domain", "Domain"),
                            ("ip", "IP Address"),
                            ("cidr", "CIDR Range"),
                            ("email", "Email"),
                            ("name", "Person Name"),
                            ("url", "URL"),
                            ("repo", "Repository"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("value", models.CharField(max_length=500, verbose_name="Value")),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="Status"
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "unique_together": {("client", "asset_type", "value")},
            },
        ),
    ]
