# Generated by Django 5.2.12 on 2026-04-05 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive Report"),
                            ("technical", "Technical Report"),
                            ("retest", "Retest Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[
                            ("docx", "Word Document"),
                            ("html", "HTML Report"),
                            ("pdf", "PDF Report"),
                        ],
                        default="docx",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("delivered", "Delivered"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "generated_file",
                    models.FileField(blank=True, upload_to="reports/%Y/%m/"),
                ),
                ("template_used", models.CharField(blank=True, max_length=100)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
