# Generated by Django 5.2.12 on 2026-04-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CorrelationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("engine_used", models.CharField(max_length=50, verbose_name="Engine")),
                ("input_summary", models.JSONField(blank=True, default=dict)),
                ("output", models.TextField(verbose_name="Analysis Output")),
                (
                    "attack_chains",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Attack Chains"
                    ),
                ),
                (
                    "patterns",
                    models.JSONField(blank=True, default=list, verbose_name="Patterns"),
                ),
                (
                    "risk_priorities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Risk Priorities"
                    ),
                ),
                (
                    "executive_summary",
                    models.TextField(blank=True, verbose_name="Executive Summary"),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "remediation_plan",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Remediation Plan"
                    ),
                ),
                (
                    "business_impact_analysis",
                    models.TextField(
                        blank=True, verbose_name="Business Impact Analysis"
                    ),
                ),
            ],
            options={
                "verbose_name": "Correlation Result",
                "ordering": ["-created_at"],
            },
        ),
    ]
