# Generated by Django 5.2.12 on 2026-04-05 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("correlation", "0001_initial"),
        ("engagements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="correlationresult",
            name="engagement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correlations",
                to="engagements.engagement",
            ),
        ),
    ]
