# Generated by Django 5.2.12 on 2026-04-05 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("domain", "Domain"),
                            ("ip", "IP Address"),
                            ("cidr", "CIDR Range"),
                            ("email", "Email"),
                            ("name", "Person Name"),
                            ("url", "URL"),
                            ("repo", "Repository"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "in_scope",
                    models.BooleanField(default=True, verbose_name="In Scope"),
                ),
            ],
            options={
                "verbose_name": "Scope Item",
                "verbose_name_plural": "Scope Items",
            },
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement_id",
                    models.CharField(
                        help_text="Format: RAVEN-EASM-YYYY-NNN",
                        max_length=30,
                        unique=True,
                        verbose_name="Engagement ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Engagement Name"),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        max_length=10,
                        verbose_name="Tier",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scoping", "Scoping"),
                            ("active", "Active"),
                            ("reporting", "Reporting"),
                            ("review", "Review"),
                            ("delivered", "Delivered"),
                            ("retest", "Retest"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("el", "Ελληνικά")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "testers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Engagement",
                "verbose_name_plural": "Engagements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EngagementDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("sow", "Statement of Work"),
                            ("roe", "Rules of Engagement"),
                            ("checklist", "Pre-Engagement Checklist"),
                            ("report_exec", "Executive Report"),
                            ("report_tech", "Technical Report"),
                            ("retest", "Retest Report"),
                            ("escalation", "Escalation Form"),
                            ("board_deck", "Board Deck"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Engagement Document",
                "verbose_name_plural": "Engagement Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreEngagementChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("items", models.JSONField(default=list)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "engagement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Engagement Checklist",
            },
        ),
        migrations.CreateModel(
            name="Retest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retests",
                        to="engagements.engagement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retest",
                "verbose_name_plural": "Retests",
                "ordering": ["-scheduled_date"],
            },
        ),
    ]
