# Generated by Django 5.2.12 on 2026-04-05 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0001_initial"),
        ("findings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retest",
            name="findings",
            field=models.ManyToManyField(blank=True, to="findings.finding"),
        ),
        migrations.AddField(
            model_name="scopeitem",
            name="engagement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scope_items",
                to="engagements.engagement",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scopeitem",
            unique_together={("engagement", "item_type", "value")},
        ),
    ]
